rules:
  indent:
    - 2
    - "tab"
    - 
      SwitchCase: 1
      VariableDeclarator: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
    
  jsdoc/check-param-names: 1
  jsdoc/check-redundant-params: 1
  jsdoc/check-redundant-returns: 1
  jsdoc/check-returns-types: 1
  jsdoc/check-types: 1
  jsdoc/newline-after-description: 1
  jsdoc/require-description-complete-sentence: 1
  jsdoc/require-param: 1
  jsdoc/require-param-description: 1
  jsdoc/require-param-types: 1
  jsdoc/require-returns-description: 1
  jsdoc/require-returns-types: 1
env:
  node: true
  mocha: true
extends: 'eslint:recommended'
plugins:
  - jsdoc
