rules:
  indent:
    - 2
    - 4
    - 
      SwitchCase: 1
      VariableDeclarator: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  valid-jsdoc:
    - 2
    - prefer:
        return: 'returns'
env:
  node: true
  mocha: true
extends: 'eslint:recommended'
