rules:
  indent:
    - 2
    - 4
    - 
      SwitchCase: 1
      VariableDeclarator: 1
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  valid-jsdoc:
    - 2
    - prefer:
        return: 'returns'
  jsdoc/check-param-names: 1
  jsdoc/check-tag-names: 1
  jsdoc/check-types: 1
  jsdoc/newline-after-description: 1
  jsdoc/require-description-complete-sentence: 0
  jsdoc/require-hyphen-before-description: 1
  jsdoc/require-param: 1
  jsdoc/require-param-description: 1
  jsdoc/require-param-type: 1
  jsdoc/require-returns-description: 1
  jsdoc/require-returns-type: 1
env:
  node: true
  mocha: true
extends: 'eslint:recommended'
plugins:
  - jsdoc