language: node_js
node_js:
  - "stable"
  - "unstable"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "unstable"
    - node_js: "0.10"
after_script: 
- npm install coveralls@2.11.6
- cat ./coverage/lcov.info | coveralls
- npm install codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token: 3d98d4400141a7f4e7ae22696ea587c6430f0ceec97dd7f9d24a49763dbb3c4a